### ISSUE TITLE
Technique doesn't work on version 2 of the CLR

### ISSUE THREAD

**Issue by shazar14** [whokilleddb/load-my-clr#2]
It appears that this technique does not work with version 2 of the CLR

![version2](https://user-images.githubusercontent.com/768586/215524290-5fa2c84a-49dd-4202-94ee-f258f66d7f88.PNG)

I have multiple versions of the CLR on my system and the code will select the first version of the runtime that it finds.  If the "break" on line 86 of customloader.c is removed then the last version of the CLR will be selected and the technique works (in the case you also have version 2 on your OS)

![verison4](https://user-images.githubusercontent.com/768586/215524299-38cdf1c9-ca7a-481a-9843-5a9f2d9d61f7.PNG)

Not sure why the technique fails on version 2 but i tested this on several systems and always get:

[!] ICLRRuntimeHost_ExecuteInDefaultAppDomain() function failed (0x8013101b)

**Comment by whokilleddb** [comment]
Hi @shazar14 can you open a PR with the fix? Thanks!
